### ISSUE TITLE
Option target might be better called provides

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#105]
Because the parameter basically says this step 'provides' certain output file.

**Comment by gaow** [comment]
Or, `yields`?

**Comment by BoPeng** [comment]
Maybe, from a snakemake camp, is it enough to do

```
[10: provides='{bamfile}.bam.bai']
input: '{bamfile}.bam'
```

**Comment by gaow** [comment]
By snakemake camp you mean the wildcard syntax, like input/output `pattern` style? I'm a bit confused because here I did not see any change in proposed syntax for auxiliary step other than using wildcard pattern and renaming `target` to `provides`. 

If you are talking about snakemake-like syntax then I would think you are saying something like:
```
[10: auxiliary = True]
input: '{bamfile}.bam'
output: '{bamfile}.bam.bai'
```
because snakemake always requires input/output keywords. But I doubt this is what you meant.

**Comment by BoPeng** [comment]
The original proposal do something like

```
[10: provides='*.bam.bai']   # only provide matching information, no pattern.
input: '${output[0]}[:-4]'   # we know ${output}, but nothing else
output:    # already known
```

The pattern is useful in that in addition to `${output}`, this one actually provides `${bamfile}`,

```
[10: provides='{bamfile}.bam.bai']
input: '{bamfile}.bam'
```
so `input` is easier. (Here `${output}` is know so it can be ignored). 

My question was how much use cases this syntax can cover.

Your syntax also makes sense though.

**Comment by gaow** [comment]
Ok, I see here snakemake style means using pattern, and I think it will be more intuitive for sure. Because here we want to mimic Make system where a lot magic are related to the use of wildcards. My syntax might look more consistent with other steps but yours is simpler.  

As for user case, I can imaging people translating Make or snakemake script to SoS script directly in this style and every step is auxiliary (yes SoS is multi-style!) ... and that does rely heavily on pattern.

**Comment by BoPeng** [comment]
DAG first ... this is the step for everything down the road but there are still many things to be done before that (e.g. better signature...) so take your time.
