### ISSUE TITLE
Collect variables, standard input and output in step signature

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#109]
We should record variable definitions, command used, and standard input and output in step signature for later reference. With a master index file, we should be able to do something like

```
sos exam job_name_or_id
```

**Comment by gaow** [comment]
This is almost like building a database from signatures and allow for queries. I think we have discussed this before. It might be challenging if a job involves many commands: same command different parameters (`for_each`), or even different commands (multiple `run`, etc. in one step). Because of that, a flat database table may not be good idea. I can think of putting them all in a `json` file, and use `pprint` or something similar to view the `json` files

**Comment by BoPeng** [comment]
Right now I have put all related variables in the signature file. Output is more difficult because not all steps produces output and command can be executed elsewhere etc. However, with existing files under `.sos/.runtime`, we can already search files and related commands ... something like

```
sos query(?) filename/command/variable
```

**Comment by BoPeng** [comment]
Implemented in the new signature.
