### ISSUE TITLE
Improve report action.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#119]
Right now report simply write the passed script to the report channel. We can however improve this a lot, by for example,

```
report(_output, style='embed', title='', float='')
```

to properly report a figure, a table etc. The figure can be linked, embedded, floated, with proper title etc. A text file (e.g. csv) can be properly formatted for markdown, HTML, latex etc. I suppose we can have a global `report_style` to control how different types of items are reported.

This can best be implemented by an extension/plugin type of mechanism so that we can easily add more reporting methods, and users can define their own extension if needed.

**Comment by gaow** [comment]
As I have suggested, I think if we provide an action for RMarkdown and can render the contents from SoS, it is good enough for most users. Being the only currently usable dynamic document generator, it can load text file to R, render it into interactive tables and graphs (the bookdown example I give in #115 ). I mean we do not have to do any additional work here. Instead we advocate the use of RMarkdown for dynamic report, which will evolve on its own. We can also easily attract the large user base of RMarkdown / Knitr. Statisticians seem to use them more, in RStudio. Not sure how popular it is amount bioinformaticians.

**Comment by BoPeng** [comment]
Then the R code would be run outside of SoS, which can be confusing... but perhaps we can describe the procedure as

1. use sos to run shell and python code and generate R markdown script
2. use Rmarkdown to perform actual data analysis and produce report.

In comparison to running R analysis in SoS and report results in markdown (mimicking Rmarkdown), this approach

Pros:

1. Can borrow all power of R/Rmarkdown, especially for users who are using RStudio,

Cons:

1. Need two steps
2.  Need to write Rmarkdown script back to SoS script for modifications to the script.

**Comment by gaow** [comment]
No, the R code will still be run inside SoS, as I suggested in #115 a few minutes ago, so this will not be a two-step procedure. We do have to `check_R_library('RMarkdown')`, and possibly `knitr`, too. 

> Need to write Rmarkdown script back to SoS script for modifications to the script.

I'm not sure why ... we write Rmarkdown script inside SoS, and modify the script also inside SoS. You can also think Rmarkdown script as an enhanced R code that can do some analysis on the fly (e.g., load data into nice tables) as well as generating some report. All we need is an `action` for it -- meaning we need an Rmarkdown interpreter which is essentially `Rscript -e 'render( ... )'`. But the implementation will not be that easy because there are various parameters possible in the `render()` function. See an example here in the README.md:

https://github.com/rstudio/rmarkdown

**Comment by BoPeng** [comment]
I see, here inside/outside of SoS is confusing because

[10]

! '''{R}
! plot(0)
! '''   
```
is NOT running anything but

```
[100]
Rmarkdown(output='output.html')
```

will run all the analysis (with R code collected during the execution of workflow). Users can choose to get the `.Rmd` file, load it into Rstudio and run the code there though.

The latter case is why I say we need to port .Rmd back to SoS because the report is unlikely to be satisfactory initially and users generally need to load the SoS generated .Rmd file to Rstudio, debug and improve it. Then if they want to generate report from SoS directly, they would like to re-apply the changes to SoS. I expect most users would go this way because SoS lacks debug and visualization features of RStudio.

**Comment by gaow** [comment]
> the report is unlikely to be satisfactory initially and users generally need to load the SoS generated .Rmd file to Rstudio, debug and improve it

I'm not sure if this is that important. Even in Rstudio, normally people just hit the `knitr` button and check the HTML or PDF generated, and if not happy they edit the rmd file, hit `knitr` again, and check the product. Here instead of editing rmd, we edit SoS and instead of hitting knitr button we run SoS again. I get your point that if a particular figure needs to be fixed then it is easier to test that chunk out interactively in RStudio. But I would not mind doing it in SoS and compile all the codes, just like change latex source and compile. I only worry that `knitr` does some caching inside RStudio which might no longer holds outside RStudio, and thus slow down the compilation ... But for light applications (vs writing a book) it should be acceptable

**Comment by BoPeng** [comment]
Replace with more specific issues.
