### ISSUE TITLE
default output report file and -r option

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#120]
Now that we do not have `-r`, we can use it to specify report generated by SoS run. If it is not specified, should we

a). dump to stdout
b). use a default name such as `$sos_script.sos.md`. 

Ideally we should give each run an unqiue ID (from sos script md5 and parameter) so that we can have different report and log file for different parameters. One problem with that approach is that it cannot reflect changes in included .sos files (nested workflow).

**Comment by gaow** [comment]
For starters we should perhaps have a global log file (like vtools there are 2 levels of verbosity), just for book-keeping purpose. And the report generated can go into the end of log file if `-r` is not specified (most likely because user does not care; thus why should we). 

As for uniqueness of report: can we attached the entire SoS script to the end of report, as a special default section, except that we remove the report text (whatever starting with `!`)? That makes a report file self-contained.

**Comment by BoPeng** [comment]
duplicate with #220
