### ISSUE TITLE
Rmarkdown action.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#121]
We have pandoc action to convert SoS generated reports, and we should also provide a Rmarkdown action to process user-generated report in `.Rmd` format to produce `html` or `pdf` outputs. Basically, users can do

```
sos run script -r result.Rmd
Rscript ... process Rmd ...
```
and we can define a `Rmarkdown` action to do the second step within SoS.

**Comment by BoPeng** [comment]
I have added a draft implementation for action `Rmarkdown`, please implement it properly and add an example and a test.

**Comment by gaow** [comment]
Great! I do not have any such examples though, because I do not document myself in `rmd` (i have a home-made tool) ... I'd like to try it out for production. Let me get hold of my colleagues SoS and post-sos rmd, and make that work. He just said he'll send me tmr. I'll create some examples if I do not hear from him by tmr.

**Comment by BoPeng** [comment]
ok, basically you will need to figure out the right command line and add it to `action.py`

**Comment by gaow** [comment]
Yes i read the code and noticed that. Also about loading the right package, and most importantly how to put in `extra_args` because unlike pandoc, rmarkdown is an R function not command switches.

**Comment by BoPeng** [comment]
It is working now, but not properly tested and documented.
