### ISSUE TITLE
Execute and convert ipynb file.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#138]
Now that we can execute SoS in jupyter, and have all the information in the ipynb file, we should provide ways to

1. convert .pynb to .sos. This means code to .sos code, and markdown to .sos report.
2. execute .pynb file directly

Now, it is also possible to convert .sos to .pynb, which would allow users to execute .sos file within the browser...

There are a few problems here:

1. SoS restrict flow of variables so variables defined in a cell is private. Variables in notebook style is by default public.

2. Are we assuming a cell <-> step map? How about numbering?

3. Are we treating ipython notebook markdown text as comment, or report? The markdown should be comments if we emphasize on the workflow side, and should be report if we empahsize the report /RMarkdown side. Report sounds nice but sos report is within steps, and ipython cells are top level citizen. Perhaps we can create a report cell type?

4. I suppose jupyter is especially suitable for our 'notebook' style use of SoS, namely everything is a list of scripts, with no section etc. I am not sure how we can introduce the rest of the features to the jupyter interface..

**Comment by gaow** [comment]
For point 2, I may be missing something here but I always consider pynb a playground where I type a lot of bad commands before coming up with a good one; and where I share a report-like analysis with a colleague. Do we really want to execute pynb without knowing how it is saved (a mixture of good / bad codes)? 

I think point 1 will be a lot easier if you only consider converting pynb to 'notebook' style SoS. As I previously mentioned I won't use pynb for things other than just being a notebook. So for notebook style natural numbering would be fine. I think the notebook markdown text should be report. Because if the notebook contain a lot of English text even turning them into comments can look messy. On the other hand can we do something with `sos show` to get some "pure" script removing comments and report? I'm not sure why we want the rest of the features with jupyter interface; but I may not be in a good position to judge given my understanding of what pynb is there for.

**Comment by BoPeng** [comment]
For the record, `ipynb` <-> `sos` conversion is implemented, works, but with very limited function. We will add more features (e.g. report) later on.

The problem with even notebook style is that all definitions have to be in the global section to be seen by other steps, and currently we are putting all of them to sections. We will see how this plays out.

**Comment by BoPeng** [comment]
BTW, I would like to concur that Jupyter is not suitable for the development or running of SoS workflows. The biggest problem is that it is like a scratch paper so user tends to run pieces of code in different cells, and it also not suitable for long running jobs. It is however, suitable for testing pieces of code (scratch paper), using it as a syntax highlighting editor/debugger, and for presenting (small) workflow with results.

I personally would write sos script in vim + ipython/sos-magic, convert sos to ipynb and run it to combine results with workflow for archiving and presentation purposes.
