### ISSUE TITLE
Execution transcript.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#141]
It is difficult to export SoS to executable python or shell scripts but it is doable to export a transcript of all statement and functions executed, with string interpolation (without assuming that the transcript is executable). That is to say, after the execution of a workflow, we can get a transcript of all scripts executed and all input and output files etc. 

Another use of transcript is for interactive use. For example, I have found it difficult to work with SoS, ipython/juputer, and RStudio if I need to execute pieces of R scripts. The problem with ipython is that it requires the execution of complete script so it is often desired to send pieces of code to RStudio. Then the `${}` stuff gets in the way. With a transcript option, we can do something like

```
%%sos -it (transcript of running in inspection mode)
R:
   read.csv(%{_input!r}) 
```

would output
```
R:
   read.csv('inputfile.txt') 
```

which can be used for debugging, and for copy/pasting to RStudio.

Another use case is to open vim with two panels, one with SoS and one with transcript. A shortcut (or command line) can be used to update transcript with changes of SoS, giving us quick response on what would be executed. Such a panel would be usable if we are developing a GUI where a transcript can be  always displayed and updated automatically with the change of SoS script.

**Comment by BoPeng** [comment]
It is implemented. Looks like another not-so-useful feature but I have found it necessary to bridge SoS and RStudio. Basically, you can check the string interpolation of a script using

```
sospaste -it
```

to run the script in inspect mode, but with transcript printed.

This is currently useful for ipython sos magic. I will add jupyter support if I use it later.

**Comment by BoPeng** [comment]
sos magic `sosset` is added to allow the addition of persistent sos options to magics such as `sos` and `sospaste`. This allows us to set options such as `-it` for the complete ipython or jupyter session.

**Comment by BoPeng** [comment]
I am not quite sure if we need to keep this feature with the introduction of new sos kernel features. Its only use seems to copy/paste transcripts to RStudio.

**Comment by gaow** [comment]
> it is doable to export a transcript of all statement and functions executed, with string interpolation (without assuming that the transcript is executable). That is to say, after the execution of a workflow, we can get a transcript of all scripts executed and all input and output files etc.

Is there a way to get the transcript "before" execution of workflows? I'm trying to leverage it for something like "export". I want to find a way to expand all the `${}` string interpretations an SoS script and write all of them to somewhere, into one text file (a transcript), without actually executing them. For example something like

```
input: ['1.txt', '2.txt']
run:
echo ${_input}
```
will give me a transcript containing 2 lines of `echo`. It's like a rough export but that'd be good enough for me. Is there a way to keep this transcript in `inspection` mode?

**Comment by gaow** [comment]
The reason I'm asking is that I currently have a very dumb SoS user case where I simply utilize SoS to generate some parameter databases. I take advantage of SoS dependency management but the rest of the job was basically `echo` parameters to files, and collect them later. When I have thousands of parameters that generates thousands of bash scripts as well as thousands of output files each possibly with a signature kept for the future which in fact will never be used again. It can take forever at this scale, but all I need is a transcript so that I can parse from there ...

**Comment by BoPeng** [comment]
Can you just run with `-p` and look in `.sos` folder for scripts?

**Comment by gaow** [comment]
Sure, but the problem is that it still generates thousands of `*.sh` files which is slightly better than generating and running them (basically echo to text files). I was hoping the `inspect` mode works, and ideally not via `open(filename, 'a')`. But that's perhaps too much to ask. Still it would be great to have it functional. I take it is still the plan because the interface does have a `-t` option.

**Comment by BoPeng** [comment]
Still do not get it, why not run the script with 

```
echo ${input} >> mylist.txt
```

**Comment by gaow** [comment]
I just want to avoid generating all those intermediate `.sos/*.sh` which is a lot of small files. For example, I have this script:

```
[some_step: sigil = "%( )"]
sequence_id = 1
sequence_name = "some_step"
n = [1000]
seed = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
output_suffix = 'rds'
input: for_each = ['n', 'seed']
output: expand_pattern('%(_n)%(_seed)%(output_suffix)')
run:
echo %(sequence_id) `basename %(_output) .rds`: | sed 's/ /_/g' > %(_output)
echo -e '  sequence_id: %(sequence_id)\n  sequence_name: %(sequence_name)\n  step_name: %(step_name)\n  exec: R\n  n: %(_n)\n  seed: %(_seed)\n' >> %(_output)

[default]
sos_run('some_step')
```

Ideally, I want to do this:

```
sos inspect script.sos -t transcript.txt
```

so that nothing will be generated under `.sos/.sh` but I get everything inside `transcript.txt`. It is not possible now and I recall you said it is not easy due to dynamic output etc. But this limitations does not apply for my case so I just want to find a way to make it work.

**Comment by gaow** [comment]
Oh, reading the help message again, I realized you did say "The transcript will be recorded in inspect and run mode but might differ in content because of dynamic input and output of scripts". So it looks like we do have an imperfect export planned though not working yet.

**Comment by BoPeng** [comment]
A lot better with an example. I will have a look.

**Comment by gaow** [comment]
Great thank you!

**Comment by BoPeng** [comment]
Try again. The problem was that you use nested workflow a lot which has not caught up with main workflow development.

**Comment by gaow** [comment]
Ha did not realize it is a bug and the fix was straightforward :) So it works with `inspect`, great!

**Comment by BoPeng** [comment]
Glad that this feature is useful to you. I was wondering if I should remove it because we have expanded scripts under `.sos/`, instant expansion in interactive mode, and report, and this transcript thing overlaps with them a bit.

**Comment by gaow** [comment]
Oh yes this is useful for this particular purpose of mine, i.e. building parameter databases with SoS, which is somewhat unique but hey others can be creative with `-t`, too!
