### ISSUE TITLE
Runtime control

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#16]
Limiting the files that the directory the step action can write to?

**Comment by gaow** [comment]
I'm not sure I get the question ... But a related thought is that in vtools we have something like temp_dir, cache_dir, resource_dir etc; we might want to setup these dirs here. But work_dir is perhaps step dependent. For example, 

```
run('cd test; python run_tests.py; cd -')
```

and it would be good if we can do:

```
with cd(test):
   run('python run_tests.py')
```

Implementation: http://stackoverflow.com/questions/431684/how-do-i-cd-in-python/13197763#13197763

**Comment by gaow** [comment]
Never mind ... I see `actions()` have a workdir option. Still it might be useful to set a default global work_dir as a runtime option.

**Comment by bpeng2000** [comment]
We should make the action functions (we need a new name) as simple as
possible. One of the biggest problems with VPT is that VPT's action needs
to be derived from a base class and it was tricky to get it right. SoS 's
action is much easier because it can be any python function + a decorator,
which controls how the function behave. Right now, the decorator ignores
the function and returns 0 directly if env.run_mode == 'dryrun', I can see
working dir is another feature that can be defined in this way.

Syntax wise we have two choices (more are welcome)

1. Add another step parameter similar to input, output and depends.
2. Create 'environment variables' such as _workdir, which is a variable
that can be defined (and recognized by SoS) and will loss its effect as
soon as the step if completed (thus the leading _).

The logic behind option 2 is that unlike input/output/depends that affect
the job scheduling, workdir are strictly local and can be handled at a
lower level. A potential problem with this approach is that action
statement can accidentally redefine a variable named _workdir and affect
the use of SoS-defined action function afterwards.

Bo

**Comment by bpeng2000** [comment]
Another option is step option, but we would better allow multi-line header
(looks awkward though) because it can be long.

Bo

**Comment by gaow** [comment]
Perhaps option 1 is easiest: add something like `runtime: workdir = xxx, mode = xxx`

**Comment by bpeng2000** [comment]
I can see it can emcompass a lot of option.

**Comment by bpeng2000** [comment]
The original issue is that we can perhaps control which directory a step can write to, namely from the point of view of the step, the file system is readonly. It can be a great security feature. For example, we can by default limit the actions to current working directory and any write activity (perhaps with exception to /tmp) would fail, and users need to add

runtime: writable=another directory

to allow that. 

I have no idea how to implement this right now.

Bo

**Comment by bpeng2000** [comment]
Some googling shows http://doc.pypy.org/en/latest/sandbox.html and AppArmor (https://github.com/edx/codejail) . This should be something we can keep in mind because it can be the biggest selling point...

Bo

**Comment by bpeng2000** [comment]
The easiest solution that do not rely too much on complex third party solution can be

1. ask users to create a sandbox account and assign r/ro permissions to resource directory etc.
2. tell sos the account user name and password in ~/.sos/settings or from command line

sos can
1. create working directory with 777 permission
2. run itself or external scripts as sandbox user, and can have access to working directory and user-allowed resource directory.
3. chown result files to the main user after the completion of the workflow.

The problem is that the sandbox user would most likely have different $PATH etc and the scripts might not run over there. We can try to carry over user's environment over there though.

Bo

**Comment by gaow** [comment]
I guess if we prepare good auto-installation script or pip/conda/binary release it should not be a big issue to use external libraries, if it makes things easier. Those sandbox have additional features such as cpu, RAM and timeout that we can utilize. But if they are very hard to configure or require root privilege then we should not adopt.

So, if `runtime` is to be added, perhaps some parameters for action() can be moved to `runtime`?

**Comment by bpeng2000** [comment]
Runtime has been added, with workdir, concurrent and blocking. The latter
two has not been implemented. Most parameters from action should be moved
their to kerp sction interface simple.
