### ISSUE TITLE
The executable usage pattern.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#215]
In VPT we used `CheckCommand` before all steps to ensure problems are found before the execution of workflows.

In SoS we used `check_command` before the command is used to provide better readability. The action will be processed at prepare stage so that absence of executables can still be found out before the execution of workflows.

With the addition of `executable()` target, a better pattern would be

```
include install_ngs_tools

[100]
depends: executable('fastq')
sh:
   fastq
```

Basically, executables now becomes dependencies so that

1. SoS will install the tool on the fly if an auxiliary step is provided to install it, 
2. otherwise report an error (target does not exist) if executable does not exist 

A related question is how to specify version to verify and install, something like

```
[10]
depends: executable(`fastq`, meta='version 2.4`)

[install_fastq: provides=executable('fastq', meta='version 2.4')
sh: run_mode='prepare'
    install fastq 2.4
```

might work.

**Comment by gaow** [comment]
The `check_command` interface is `(command, pattern)` where we can search for given `pattern` in the output of a command, not an executable. In the proposed interface, do we compare both `command` and `meta` and use exact match to look for the proper auxiliary step? Even if we can match these steps, I believe within `[install_fastq]` we need also check if version 2.4 is already available, and we will still have to use `check_command` to achieve it.  

We also have the `check_R_library` action but it works slightly differently: it actually installs R packages. Will there be problems converting this action to a target because we will not have/need the corresponding auxiliary step?

**Comment by BoPeng** [comment]
Just for the record, there is a possibility to wrap `executable` in a way to report version number, which could be used to report details of workflow (session info, #21 ).

**Comment by BoPeng** [comment]
Also note that the installation has to install programs into a path in existing `$PATH`, otherwise SoS cannot find the `executable()` after the completion of the step.
