### ISSUE TITLE
inspect only check for syntax error

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#223]
We evaluate statements in both inspect, prepare and run states, which can be wasteful in terms of performance. Because executing statement is necessary for building DAG, I propose that we stop executing any statement during inspection.

**Comment by BoPeng** [comment]
Done and close because I do not see any side effect of this change.

**Comment by gaow** [comment]
If we stop evaluating statement in prepare #230 then we only evaluate at `run`? Actually it breaks things a bit for me because for now I rely on inspection mode to run python statements without having to check existence of input / output files. It was a way to use SoS to prepare for a large simulation the proper names for input / output files without having actually creating them. I wonder what alternative option do I have?

**Comment by BoPeng** [comment]
I suppose we can have a `dryrun` mode/command which is NOT a step before `run`... It would work more or less like our current `prepare` mode.

**Comment by gaow** [comment]
Sounds good! But what will it do exactly? I take it that it will not download resources as `prepare` does. It should not execute scripts. But it will perform evaluation and run all the python statements. What else does it do?
