### ISSUE TITLE
Shared variable does not apply to `paired_with`

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#254]
Here is the MWE:
```
[work_1: shared = {'data': 'output'}]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}'
output: expand_pattern('{_name}.out')
run:
  touch ${_output}
  
[work_2]
input: "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}', paired_with = ['data']
output: expand_pattern('{_name}.out2')
run:
  touch ${_data} ${_output}
```
and the error:
```
INFO: Executing work_2: 
INFO: Executing work_1: 
INFO: work_1 input:    ['1.txt', '2.txt']
INFO: Step work_1 (index=0) is ignored due to saved signature
INFO: Step work_1 (index=1) is ignored due to saved signature
INFO: work_1 output:   ['1.out', '2.out']
ERROR: Failed to execute workflow work
[work_2] ValueError:
	Failed to process input statement "1.txt", "2.txt", group_by = 'single', pattern = '{name}.{ext}', paired_with = ['data']
: Variable data does not exist.
[work] RuntimeError:
	1 failed step: work_2
```
Perhaps it is another name scope issue?

**Comment by BoPeng** [comment]
The is the tricky part of static analysis. Basically sos looks for "variables" used in `work_2`. Because it `data` is a string, not variable, it appears to SoS that `data` is not used  by `work_2`, and because `work_2` has its own input, it does not depend on `work_1` and execute in parallel to it.

**Comment by BoPeng** [comment]
The first solution is to perform better static analysis but in theory people can do

```
var = 'da' + 'ta'
input: paired_with=var
```

which makes it impossible to detect the use of `data`. 

The second solution is to use variables such as

```
input: paired_with={'_data': data}
```

which has added flexibility to do

```
input: paired_with={'_my_index': range(10)}
```

instead of

```
my_index=range(10)
input: paired_with='my_index'
```

**Comment by BoPeng** [comment]
Fixed in https://github.com/BoPeng/SOS/commit/837d9dffbc7448c1ae757c2c8aac3888259c0cc3 

The patch partially evaluate `input:` and look for values for parameters `paired_with` and `for_each`.  It adds constant strings to `envrion_vars`. If `var` is a variable, it is either a global variable that sos recognizes, or a undefined local variable that sos does not recognize. SoS will fail to analyze the step in the latter case, and treat the step as having `Undetermined` input and execute it after the previous step.... which is certainly acceptable.

Whether or not we should allow

```
input: paired_with={'_my_index': range(10)}
```

can be the topic of another thread.

**Comment by gaow** [comment]
Great! It does look appealing to have the map style, but I guess we can wait when there is a need.
