### ISSUE TITLE
Run SoS on cluster

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#30]
VPT has some support for running on cluster; I'm wondering if they are mature enough to be ported to SoS?

**Comment by bpeng2000** [comment]
It has something called submitter that run commands in background or on
cluster. It worked but more or less a hack. Let us see if there is any
other option.

**Comment by bpeng2000** [comment]
We need to lean Python Celery library and see if it can help us distribute jobs on cluster systems.

**Comment by bpeng2000** [comment]
It seems that we cannot go around PBS/Torch stuff. Let us think of a good interface for it. I would propose that we use runtime options such as 

```
[1]

run:  ncpu=5, ...
   large job
```

and in `~/.sos/config.json` we have configuration of the PBS system.

A promising python library is [drmaa](http://drmaa-python.readthedocs.org/en/latest/tutorials.html) because it interacts with PBS and SunGrid stuff, but it requires a C library which is not installed with `pip install drmaa`.

**Comment by bpeng2000** [comment]
Our cluster does not support drmaa and the admins are not thrilled by the idea of controlling pbs/torque from a programming interface potentialling bypassing some rules and filters. I suppose we will have to use commands to submit and monitor jobs. This seems to be the approach taken by snakemake.

**Comment by BoPeng** [comment]
I have been thinking about this a lot and I seem to conclude that that submitting tasks as PRS/DRMAA/SunGrid jobs is a bad idea. The main problems are that

1. It is difficult for SoS to know the status of the jobs and cannot monitor the progress of them.
2. It is difficult to recover from fault.
3. It is difficult to submit large amount of small jobs or jobs with undetermined sizes because all the jobs have to be waiting in the queue, and users have to be clever in how they group small jobs.

It would be better to take a celery or rq (redis queue) approach in that

1. We start sos and the tasks are queued.
2. We start one or more sos workers by submitting jobs to the cluster. SoS should know the capacity (walltime, cpu, ram) of these workers.
3. sos would send jobs to the workers through celery or rq. runtime options can tell sos how long the jobs will take and submit them to appropriate workers with load balancing.
4. Users can monitor the jobs through flower (celery) or rq monitor.
5. If workers are full, we can submit another worker to the cluster. If some works are idle, they can die naturally or sos can kill them.
6. several sos scripts can share the same workers.

**Comment by gaow** [comment]
Is there an example how redis queue works with cluster? I find it difficult to wrap my head around it. I'm always under the impression that you cannot bypass `qsub` or `sbatch` or whatever commands that interacts with the cluster directly. If there exists a universal solution then even using SoS as cluster job manager would sound very appealing -- I must be missing something here.

**Comment by BoPeng** [comment]
Frankly I do not know. I just imagine that as long as cluster nodes can communicate with the head node (or another master computing node), this should work. I will take a deep dive to the rd and perhaps ask some questions there.

If this works, it would be way better than the qsub approach.

**Comment by BoPeng** [comment]
Asked https://github.com/nvie/rq/issues/705 .

**Comment by BoPeng** [comment]
Ok, finally something specifically designed for PRS/Torque, 

http://ccl.cse.nd.edu/software/workqueue/ that works in a way similar to rq (I think).

discussed from https://www.reddit.com/r/Python/comments/2y8a2l/distributed_computing_using_celery_dispy_parallel/

**Comment by gaow** [comment]
Looks promising! The makeflow source code is in C though but it does have a lot of `dag.*` that seems to be very much relevant, though not sure if we can leverage it.

**Comment by BoPeng** [comment]
We can borrow code but my understanding is that we will need our own dynamic DAG (e.g. from adage) and then send the tasks to different backend depending on different running environment. WorkQueue looks promising because the execution model, but we can also use celery (as in adage), rq, hadoop etc...

The way to use sos would be like 

1. develop the workflow without worrying about `task`
2. review usage from sos local runs, I added this function yesterday.
3. determine large jobs and insert `task` before them. As I have said insertion of task should not affect the logic as we currently do about `$output`.
4. set up running environment / backend 
5. tell sos to work with certain backend to get the `task` executed.
