### ISSUE TITLE
Convert between ipynb and SoS

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#309]
A big reason I do not like jupyter notebook is that the ipynb file is huge when there are many figures generated. These are not good to push into github for research projects. R Studio can "knit" Rmd files to HTML so one would only need to save Rmd files which is plain text. This is neat. So I want to leverage `sos convert` for the same goal: 

```
sos convert Untitled.ipynb test.sos
sos convert test.sos test.ipynb
```
My hope is to compile ipynb to sos, save it in github, and recover it to ipynb when there is a need. However `sos convert` from sos to ipynb seems to put all cells into one. This is before converting when there are 2 cells:

![2016-12-08-10-51-24_scrot](https://cloud.githubusercontent.com/assets/917985/21018907/540741ac-bd34-11e6-8262-421cc0510077.png)

This is after converting when 2 cells are merged to one:

![2016-12-08-10-51-08_scrot](https://cloud.githubusercontent.com/assets/917985/21018914/599efd26-bd34-11e6-93ca-e3737e6f7d05.png)

I do not recall if this was the behavior before. Is this a bug? It would be great to get it work so that I no longer have to version control ipynb.

**Comment by BoPeng** [comment]
This is certainly a bug. Let me have a look. Back convert should split by `%cell`.

**Comment by BoPeng** [comment]
The basic usage is fixed (broken due to restructure of code, but the test case only check if conversion is successful, not the content). You can do

```
sos convert file.sos file.ipynb
sos convert file.ipynb file.sos
```
you can also manually `File->Download as sos`, and add `%cell` lines directly in `.sos` files. `%cell` is assumed to be `code` while some strange syntax would be needed to add `%cell markdown` directly in `.sos` file (prefix by `##!`). These lines would be ignored in batch mode.

**Comment by BoPeng** [comment]
Also see #311 , which can be very helpful to reconstruct the `ipynb` file with result as long as the running environment keeps the same.
