### ISSUE TITLE
Use SoS version of ipynb for documentation

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#321]
I started using `sos convert` to make SoS scripts from my notebooks for version control. I find it quite pleasing. I now have diffs that makes sense and I no longer have to worry about saving a lot of notebook embedded figures in my github repos (though the latter is less of a concern for SoS docs). I'm wondering if we want to do the same for SoS documentation. Basically we still edit on ipynb files but we keep them local to our own computers. So what we do is:

1. `git pull` and do step 5
2. open the ipynb thus generated and make changes
3. Convert completed ipynb to SoS
4. Version control SoS scripts
5. SoS to ipynb, execute it
6. Executed ipynb to HTML

It sounds a lot of steps but we can improve `release` script to automate it. It has many advantages, eg., better merge conflict handling, tests to SoS itself #313, human readable text docs. The question is should we make ipynb completely local, or we still stick to ipynb but just "refresh" it via such conversion from time to time?

**Comment by BoPeng** [comment]
What would be the downside of keeping ipynb? Size of repository? The current arrangement works ok, at least I do not have to re-generate ipynb when I switch computers, and it is much faster to convert from ipynb to html (sos convert sos ipynb --execute takes time).

I would propose that we add a `[refresh-doc]` action in `release`. It is difficult to keeo ipynb invariant during this process (due to minor differences and for example version of R), but at least we will be able to catch errors if a notebook fails to run.

**Comment by gaow** [comment]
The biggest problem with ipynb on github is its `diff` content which can be quite noisy particularly when there are changes on objects like figures. But for the case of SoS docs it might be less of a concern -- we are mostly just text. I think github should be able to handle merge conflicts of ipynb from different collaborators. We can see if we run into that problem when we all edit the same page same time. I have no issue keeping ipynb as is for this project. I'll add the refresh doc section @BoPeng proposed as I start editing the doc pages.
