### ISSUE TITLE
All bout the -j option.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#35]
This is a thread devoted to the parallel execution feature of SoS. Basically, we need to write or find an existing implementation of DAG. Adage (https://pypi.python.org/pypi/adage/0.1.7.1) looks like a close match but we will need further investigation of this package.

[Celery](http://www.celeryproject.org/) is something we can use. It would allow us to expand to the server environment because it would become user's responsibility to set up the Celery environment for SoS to run across nodes.

**Comment by gaow** [comment]
It is extremely slow on my end to browse either site but from reading the home pages they both look promising for the job! As long as installation can be done via pip it should not be a problem to set it up.

**Comment by bpeng2000** [comment]
I have implemented a simple version of parallel execution that allows step processes within the same step to be executed in parallel. This is very crude but to do that I have already had to change SoS syntax to execute step processes in separate processes independent of SoS itself. This is certainly necessary otherwise no step process can be executed safely outside of SoS (e.g submit to Celery as independent task).

I am using multiprocessing pool but we can switch to python 3's async libraries or Celery as long as we have the DAG correct. I suspect that we can switch backend executioner for different running environment.

**Comment by gaow** [comment]
Great and looking to test this feature in the next couple of days!

**Comment by bpeng2000** [comment]
Celery is officially used in SoS now because a multiprocessing bug (feature) prevents us from spawning a new workflow from a workflow step (nested workflow). `Celery.billiard` is used and works ok now.

Note that we do not need to have a DAG to execute steps in parallel. I mean, all we need to do is 

1. get the dependencies of all steps.
2. put all steps in a pool, and execute any step (up to -j) with met dependencies.
3. Whenever a step is completed, update the pool and execute one or more steps with met dependencies. 

SoS is now Celery ready (things are submitted in separate processes) so we can easily extend the code to cluster after the above is done.

**Comment by gaow** [comment]
Great! But I noticed big performance issues after I upgraded. For example this one 
[test.sos.txt](https://github.com/bpeng2000/SOS/files/196510/test.sos.txt)  

Command `sos run test.sos.txt DSC -d` takes 12 seconds which I  believe was 1 second before the update. Is it the same problem on your end, or something is wrong about my packages?

**Comment by gaow** [comment]
I just worry that the slowness is proportional to the number of commands implied by the script (e.g. concurrent for loops) ... in that case parallelation with celery will actually harm ...

**Comment by bpeng2000** [comment]
The problem is with the `pool.close()` and `pool.close()`, which waits about 1 s. So there is about 1 second wait for the completion of each workflow and your example is the worst because it has 9 workflows. I am still investigating because some `pool.close` is fast.

```
ERROR: start waiting
ERROR: Step completed 0.006140947341918945
ERROR: Step completed 0.0060999393463134766
ERROR: results returned 0.007298946380615234
ERROR: wait join 1.0097160339355469
ERROR: Step completed 3.094782829284668
ERROR: start waiting
ERROR: results returned 1.7881393432617188e-05
ERROR: wait join 9.083747863769531e-05
```

**Comment by gaow** [comment]
If the slowness is on workflow level then I agree we can live with it. There must be good reason celery decides to wait. But it is interesting the wait time differ by several magnitudes!

**Comment by gaow** [comment]
Not sure how easy it is but if we make `-j1` not using celery at all then at least dryrun will not be that frustrating, e.g. faking a "null" interface after celery and use that for `j1`.

**Comment by bpeng2000** [comment]
I have further investigated this issue and it turns out that `pool.join` is slow. The fast join is when there is only one process. The current behavior is wrong anyway because '-j1' should not trigger pool even when `concurrent=True`. I have fixed this issue so your example should run in sequential mode, and be fast without all the overhead of processes.

Overall I do not think this is an issue because step processes are supposed to be running much longer than 1s and can benefit from multiprocessing. Fast processes should be put without or before `process` so they will always be executed sequentially. SoS certainly allows such flexibility.

**Comment by gaow** [comment]
Good! I confirm `j1` works and I agree the overhead is acceptable.

**Comment by bpeng2000** [comment]
If I understand correctly, a so-called celery cluster requires us to 

1. start celery worker process on a few computing nodes
2. start message passing between nodes
3. distribute tasks to workers 

I like this approach because the current VPT approach requires us to use `ssh headnode qsub jobs` to submit big jobs and we have no control over the submitted jobs and can only quite or wait for the completion of the tasks.

Also, the `celery.group` etc and flower monitor system might be helpful for us.

**Comment by bpeng2000** [comment]
http://dask.pydata.org/en/latest/ also looks promising.

**Comment by bpeng2000** [comment]
You can also have a look at snakemake's dag class. At this point we can actually learn many things from snakemake, such as dag, cluster support etc. It is called stealing though. :-)

**Comment by gaow** [comment]
Yes that's a 900 lines of python script. I was under the impression it requires the graph structure known at the beginning, thus I thought may not be a good option. Will see if that's the case.

Snakemake cluster support might have problems, though:

https://bitbucket.org/snakemake/snakemake/issues/84/high-virtual-memory-on-cluster-master-and#comment-13180538

**Comment by bpeng2000** [comment]
I see from the thread that snakemake runs on each node ... this is not what I have in mind because I would like to send the jobs to computing nodes. But that approach has the advantage that it might run a whole branch of jobs, instead of a single job, on a node...

**Comment by gaow** [comment]
To me, if we cannot interact with the cluster directly and have to rely on qsub like snakemake, it is no better than we support an `--export` command that prepares all the sources and export commands / scripts to 'parallelable' batches, so that users can easily submit jobs. I think this is also easier to troubleshoot. On cluster system it helps to be more transparent. Attempts to interact with it may be ill-fated. The question on that thread may well be cluster environment specific but it ended up becoming snakemake's headache.

**Comment by BoPeng** [comment]
Discussed on more specific threads.
