### ISSUE TITLE
Check R libraries

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#62]
I remember we had this action in VPT. Shall we port it over to sos actions? Once it is ported over to SoS I'll add more features to it -- for example  do not think it has an option to install R packages from github, and we cannot specify specific versions from cran.

**Comment by bpeng2000** [comment]
I have ported that action over and named it `check_R_library`. I am not sure if it should be called `check_R_libraries` because it accepts multiple libraries. My name convention is to use plural name for function and parameter names that accept multiple items even if they also accept single item.

Note that like all `check_` actions, this action is available in both `dryrun` and `run` mode.

**Comment by gaow** [comment]
Great, thank you Dr. Peng. I think yes you should stick to your convention. I'll make changes to it later today or tomorrow for github support and version number support, and send a pull request.

**Comment by bpeng2000** [comment]
It is not just about naming. Python recommends

```
import os
import sys
```

over
```
import os, sys
```

and I tent to think

```
check_R_library('A')
check_R_library('B')
```
looks nicer than

```
check_R_libraries(['A', 'B'])
```

We also have

```
check_command(['tophat', 'STAR'])
```

and we should perhaps disallow the list input and use

```
check_command('tophat')
check_command('STAT')
```

Otherwise we also need to rename `check_command` to `check_commands`.

On the practical side, separation of commands makes the implementation a bit easier and also separate errors. if we are running a script in dryrun mode and collect all `RuntimeErrors`, the multi-command form is more likely to get exact line number and more accurate error messages such as which library/command is not available.

Also the single form input allows easier expansion of interface. For example, the single form makes it easy to do

```
check_R_library('edgeR', '1.0.3')
```

and replace `search_output` with `check_command`

``` 
check_command('tophat -v', '2.1.0')
```

if we want to do so.

**Comment by gaow** [comment]
Yes I was looking at the interface and find it indeed awkward to have something like `check_R_libraries([('edgeR', '1.0.3'), ('limma', '3.2')]` or `check_R_libraries(['edgeR', 'limma'], ['1.0.3', '3.2'])`. It now looks to me like we should disallow multiple library checks with that command.

**Comment by bpeng2000** [comment]
Can I leave this to you? Basically you need to simplify `check_R_library`. The code should be easier because you do not need to write the result to a temporary file and check libraries one by one. I am not sure how to check version number, but perhaps there is some R code for that. I believe you also have to allow for multiple versions, and have to use regular expression, multiple values, or something like `1.0.3+`. 

Please also change `check_command`, and because `search_output` is awkward now, it is better to merge it to `check_command`.

**Comment by gaow** [comment]
Yes sure. I'll create a pull request after I'm done with it tomorrow.

**Comment by gaow** [comment]
I agree we should support multiple version and things like `1.0.3+`, `1.0.3-`(??). In R there is this function of `packageVersion` to check version but I looked into cran and bioconductor -- it is not possible to specify which version to install! There are [hacks](https://gist.github.com/viking/1503736) but it is difficult to handle package dependency of old versions. For bioconductor it is simply impossible -- you always get the latest version.

Should we only "check" the R version and report that as a status? e.g. a new status called "VERSION_MISMATCH"? The behavior of VERSION_MISMATCH will be a warning message not error.

**Comment by gaow** [comment]
I just submitted a patch implementing what I proposed above. 

After we merge and resolve this ticket, I wonder if we could release version 0.5.5 to reflect changes particularly with celery, a big step forward. I actually would like to learn release on github and release to pip so it would be great if you could briefly tell me how to do it, and I'd like to have a try for version 0.5.5 release. Thank you!

**Comment by bpeng2000** [comment]
I will merge the change. Releasing on github is easy. You just go to releases and create a new release if you have proper privilege. Releasing on pip is also easy but sos is released under my account (very old one named simupop) and I do not know if it allows multiple people to release.

**Comment by bpeng2000** [comment]
Several issues:

1. `check_command('ls -l')` would fail because `ls -l` is not a valid command. However, `check_command('ls -l', 'something')` is valid because `ls -l` can produce result with `something`. I think we should run `ls -l` if the command name include space (use `shlex` to be more rigorous).

2. We currently ignore return value of command when we execute the command and check its output, because some command returns non-zero with a usage/version message if it is called without option. However, sometimes the user might want to check the return value of a command, for example, to test if the command has a certain option. I think we should produce a warning message if the command does not return 0.

3. I am not sure how this action respond to malicious code such as

```
check_command('rm -rf *')
check_command('cat <')
```
The former will remove all files and the later might freeze and wait for input. 

4. We should unify the way users check versions. `check_command` uses regular expression and multiple values so users can do

```
check_command('STAR', ['1.2.3', '1.2.4'])
check_command('STAR', '1.2.[3-6]')
```
although the first one actually accept version `11223` because of the  dot matches everything.  I have not read the details of the implementation of `check_R_library` but we should probably unify them.

**Comment by gaow** [comment]
For issue 1: yes I think `shlex` will do the trick.
Issue 2: I agree, and to be consistent, should we check the return status of every script action and give a warning if they are not zero? 
Issue 3: I am not sure either ... 

For the `check_command` `pattern` option vs. `version` option in `check_R_library`: because `pattern` serves a much more general purpose than version checking, it makes sense to use regex there. But for simple version check, particularly in R, what will be used most is >= some version. R does not even allow one to go for a history version easily. So currently the `+` syntax e.g. `1.0.0+` for R versioning should satisfy typical needs. I just worry for R users it is unfair to force them to use python regex when all they want to do is to check a version number.

**Comment by bpeng2000** [comment]
OK,

1. Please use `shlex.split()` to check input and run the command if it contains options. I guess we do not have to run a command without option. 

2.  execute script would raise an `RuntimeError` if return value is not 0. We should give a warning for `check_command`. We need more than `check_output` though. We should also return the return value to SoS in case users would like to do something with it.

3. `dryrun` should not do anything to the filesystem but unfortunately we cannot really enforce this (at least for now). Can we at least disallow pipeline and redirect?

4. I see your argument. Hopefully we can document these well.

I just submitted a patch with two tests for the behavior.

Then there is this `strict_versioning` parameter. Frankly speaking I do not like it because we tend to use it a lot, and we tend to give a dedicated command line parameter  to turn it on or off. Perhaps we can have a command line option such as by default we do not run a script with any warning (and force users to look into the warnings) and if users insist they can bypass warning and run? This is more or less like the `gcc` fail on warning or treat warning-as-error thing.

**Comment by bpeng2000** [comment]
Your latest patch that replaces

```
SoS_ExecuteScript(install_script + version_script, 'Rscript', '.R').run()
```

with 

```
 R(install_script + version_script)
```

is incorrect because `R` is only executed at `run` mode, and `check_R_library` is designed to run at both `dryrun` and `run` mode.

**Comment by bpeng2000** [comment]
Can we replace `strict_versioning` with something like

```
fail_if(check_R_library( ...) != 0, "Strict version is required.')
```

here `RuntimeError` is the first level of error (for library not found) and return non-zero is the second level of error (for version mismatch) and users can choose ignore the second level error in their script. Of course we also yield a warning message for version mismatch.

**Comment by bpeng2000** [comment]
Because `check_command` is supposed to check the existence or basic usage of commands, I terminate `check_command` after 2 seconds to ensure we are not stuck at this action. I however notice that this does not work for all cases, for example,

```
check_command('sleep 10')
```

would terminate after 2 seconds but

```
check_command('cat > /dev/null')
```

does not.

**Comment by gaow** [comment]
Good idea on strict versioning, now that we have return status recorded. It's a good example so let me add the usage to the wiki page.

**Comment by gaow** [comment]
Never mind, I see you have updated it already :+1:

**Comment by bpeng2000** [comment]
In the old days where VPT was not flexible enough, `strict_versioning` was required (but I was tired of using it). I think we can use this two level error mechanism throughout the definition of SoS actions.

**Comment by bpeng2000** [comment]
The problem with 

```
check_command('cat > /dev/null')
```

not exiting has been fixed by setting a global timeout limit (5 seconds) for all expressions and statements executed in `dryrun` mode. This ensures we can execute any script in finite time in dryrun mode and report problems. For this particular case, `sos dryrun script` would report a timeout error after 5 seconds. Details of this behavior is documented at https://github.com/bpeng2000/SOS/wiki/Documentation#dryrun-prepare-and-run-mode

**Comment by BoPeng** [comment]
I notice that pip uses the following syntax for version control,

```
SomePackage             # latest version
SomePackage==1.0.4      # specific version
SomePackage>=1.0.4      # minimum version
SomePackage>=1.0,<=2.0  # minimum and maximum version
SomePackage>1.0         # higher than 1.0
```

Do you want to adopt this?
