### ISSUE TITLE
SoS export

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#63]
Is there a plan to implement this interface? It is helpful to have the export feature for debug and for portability.

**Comment by bpeng2000** [comment]
This is something that can be done but very difficult to do perfectly/beautifully, because the execution path of SoS can be dynamic. For portability, if we export something that depends on sos utility and action functions, it might be easier to install sos. For debugging purposes, we might as well implement some feature that output e.g. interpolated scripts during run/dryrun. I mean, something like

```
sos run -t transcript_file script ...
```
and in the transcript file there are all the statement being executed etc. The transcript cannot be run directly because not everything is recorded and because of parallel execution stuff, but can help user to, e.g. execute the last shell script from command line if something went wrong.
