### ISSUE TITLE
options to interpreter for SoS actions

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#66]
Right now we have

```
action:
   script
```

or

```
action(script)
```

with default parameters. It makes sense to allow customized command line arguments for interpreter (e.g. `python -m module`) or allow users to pass command line arguments (e.g. filenames). It is difficult to determine a syntax though. We can do

```
python -m cProfile:
   script
```
or

```
python:   args='-m cProfile'
```

which are both

```
python(script, args='-m cProfile')
```

The second form can be extended to something like anything that is not a valid runtime option will be passed to the action.

A similar but different topic is commands such as `docker build`, with `build` hardly an argument. The current approach would be

```
@SoS_Action(run_mode=['run'])
def docker:
    ... interpreter='docker build'
```

but `docker` is not informative and we might face programs with multiple subcommands that accept a script. Something like

```
docker build:
   script
```

might make more sense.

**Comment by gaow** [comment]
> The second form can be extended to something like anything that is not a valid runtime option will be passed to the action.

But if there is a name conflict with any runtime option we'll have a problem. Also should we promote the python motto that there is "only one way to do it"?  For example we can use only

```
python -m cProfile:
  script
```
and only

```
python(script, args='-m cProfile')
```

**Comment by bpeng2000** [comment]
I have also encountered cases such that the interpreter (`docker build`) does not accept a filename. It assumes a directory name with `Dockerfile`, and with `-f name` if `name` is not `Dockerfile`. Because of this, I have changed the interpreter to something like `bash ${script!q}`, which allows manipulation of command lines.

I agree that name conflict can be a problem. Perhaps we can stick to `args`, or even more flexible form of 

```
action_args={'args': '-c Profile', 'someother': False}
```

**Comment by bpeng2000** [comment]
I have submitted a patch that

```
action: runtime_options, action_options:
    script
```

is equivalent to

```
process:  runtime_options
action('script', action_options)
```

In real implementation, all options are passed to `process` and to `action`, but they are filtered in both places depending on if the the parameter is a runtime option or not.

This change allows the use of

```
docker_build:  tag='mytag', rm=True
   Dockerfile
```

SoS actually does not know (and cannot check) what parameters `docker_build` accepts because this function accepts a lot of parameters (https://docker-py.readthedocs.org/en/stable/api/#build).

**Comment by gaow** [comment]
What is the current syntax though? For example if I want to run `python -W ignore` how should I specify? I did not find it on the wiki ...

**Comment by bpeng2000** [comment]
This has not been implemented because we do not know where such options
should be inserted. I suppose the safest way is to allow specifying the
complete interpreter but I have not found a good syntax.

Bo

**Comment by BoPeng** [comment]
Fixed. Although option `args='-n'` etc is not general enough to handle all cases, it can handle most cases with least complexity.
