### ISSUE TITLE
SoS clean

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#72]
I propose a feature `sos clean workflow_name` where SoS looks for the output in specified workflow and remove all of them. I think it helps maintaining a project.

**Comment by bpeng2000** [comment]
Well, we currently does not restrict the location of output files...

**Comment by gaow** [comment]
Yes ... I was just thinking that SoS collects all `step.output` in dryrun mode and in `clean` try to remove them if exist. For research projects using git, it is not a big deal because we can always run `git clean`; but outside git if we do not want to keep intermediate files (from intermediate steps) it would be easier to remove them all systematically.

**Comment by bpeng2000** [comment]
There are two types of files here, `step.output`, and other intermediate files. 

1. Removing `step.output` is easy but has the side effect of having to repeat a step if the output file is needed later (e.g. for next step).
2. Removing other intermediate files is difficult unless users can tell us 'remove all files except for `step.output` under this directory. This is useful to get a clean tree with only required files.

This is actually another feature that VPT has but I am not sure if it is useful enough to port to SoS. Namely a feature that replaces large intermediate files with their signature. Basically `file` is replaced with `file.info`. The file is viewed by VPT as 'existing' for signature comparison so unless the actual file is used, a step can be skipped without the actual file. I think we can implement this with option 1, namely we keep file information after we remove the files so that we can continue to analyze and repeat the execution of workflows are the removal of the actual files.

**Comment by gaow** [comment]
I was not expecting we do 2 ... actually I always think this VPT feature was a good one. Getting rid of half-baked BAM files without breaking up the pipeline can save a lot storage and time porting projects. I mean we'll sooner or later run into that situation again, only in much larger scale as the cost of generating WGS samples keeps dropping. 

Are there other VPT features that have not been ported? For what is worth considering, perhaps start another ticket of a "task list" to keep track of them? 

- [ ]

**Comment by BoPeng** [comment]
Now that the need for `RemoveIntermediateFile` is satisfied by our file signatures, the remove subcommand can do

```
sos remove [file] -s -d -f
```

where:

1. `sos remove -f` removes all intermediate files that are not tracked by sos.
2. `sos remove -d` also removes all directories
3. `sos remove files` removes files and signatures of specified files.
4. `sos remove files -s` removes only signatures of specified files
5. `sos remove -s` removes all run time signatures.

**Comment by BoPeng** [comment]
Implemented with option `-n` (dryrun), `-f` remove untracked files, `-d` remove untracked directories. Will add more options if needed.

A problem with this command is that we usually run script from the script directory, and the script itself is not tracked, and could be removed. This is certainly very dangerous.

**Comment by BoPeng** [comment]
The current solution is to disallow cleaning current directory. Users have to specify one or more subdirectories to be cleaned. This is safer and encourages keeping results of runs in dedicated subdirectory.

**Comment by BoPeng** [comment]
Implemented.
