### ISSUE TITLE
Option to run sos script inside a docker image.

### ISSUE THREAD

**Issue by BoPeng** [BoPeng/SOS#87]
Right now our syntax is used to run individual steps in different docker image. We should also have an option, cannot be `-d` because it is used by dryrun mode, but can be `-i` (image) or `-w` (with), such that

``` 
sos run script.sos -w docker_image
```

would execute the script inside docker. The problem is that the docker container might not have sos installed but perhaps we can install sos on the fly.

**Comment by tiagoantao** [comment]
Installing SOS on the fly is not a trivial endeavour: Do you have Python on the container? If yes, which version? Want to install it, well that can vary a lot with the Linux distro inside the container...

**Comment by bpeng2000** [comment]
I understand. We can also export sos scripts to python scripts, or wrap SoS into a single executable (using pyinstaller and the like) but because SoS script can in theory use any python module, we will have to provide a full python 3 installation if the container does not have it (and that can easily break existing container service).

We can also mount local python3 and sos to docker container but even the os module would break because of the OS difference between docker/linux and host machine (mac in my case).

I think the safest solution is to assume a common docker image for all steps if a docker image is provided from command line, but then there is no way to provide step specific docker run options (e.g. volumes)...

**Comment by BoPeng** [comment]
Not possible for full automation as far as I can tell...
