### ISSUE TITLE
Runtime signature duplicates

### ISSUE THREAD

**Issue by gaow** [BoPeng/SOS#97]
I noticed that SoS runtime signature will only "stabilize" after more than one runs. This same example will demonstrate my point [simulation.txt](https://github.com/BoPeng/SOS/files/228993/simulation.txt):

```
cd test; rm -rf .sos
sos run simulation.txt -v0
ls .sos/.runtime/*info | wc -l
```
Output is 290. Now run it again. Supposedly it should reuse all output and signature count remains the same:
```
sos run simulation.txt -v0
ls .sos/.runtime/*info | wc -l
```
Output is now 374. Looking into it I noticed some files with duplicated signature -- same content but different MD5 number. Now running it again the counts remains at 374. So it takes 2 runs to "converge". 

I noticed this in my application because re-running does not skip existing results. It usually takes 3 to 4 times for my case! I made this example to reproduce the behavior to some extend, hopefully is enough to help track down the culprit.

**Comment by BoPeng** [comment]
This should have been fixed now. The problem was that the dynamic code requires we use filenames saved in signature files to refresh `output` but the signature file saves full path names, leading to different signature filenames with the same content.... (you do not have to understand the reason .. :-)

**Comment by gaow** [comment]
Great! It works as expected. I looked at the patch though and realized the use of os.path.realpath is crucial. I take it that os.path.abspath will work, too? I looked at documentation of os.path.realpath. It seems a safer os.path.abspath to me. 

Thanks a lot! That makes my long running scripts a lot less frustrating.

**Comment by BoPeng** [comment]
I tried not to break any test but our test cases are still not enough.

Bo

**Comment by gaow** [comment]
Just out of curiosity, how should we unit test this case? It's a good thing that we test it a lot in production so perhaps do not feel too bad for not having everything in unit-tests :)

**Comment by BoPeng** [comment]
We have a test case for runtime signature where `time.sleep(1)` etc are used as actions. We record the time needed to run a script in the first time (or with -f option) and the second time and assert that the first run should take more than 2 seconds and the second run should use less than 1 second etc. This bug was not detected because it involves the use of runtime signatures in the second step. What exactly happened was

1. we output file `a` and save signature as `/path/to/a md5`, we use `a` as the input of second step and save signature.
2. we run the test again, the first step is skipped and we obtain the filename `/path/to/a` as the output of step 1 and input of step 2, and the signature does not exist for `/path/to/a`, so we rerun and create another signature.

The patch makes sure we save `a` instead of `/path/to/a` in signature file. I will create a more complicated test later (have another presentation on Friday).

**Comment by BoPeng** [comment]
BTW, before or at least shortly after your DAG work, you should define a series of tests with different types of input/output (undefined, defined, dynamic, multiple sources etc) and intended DAG. Something like

```
script = ...
wf = script.workflow()
dag = wf.prepare()
self.assertEqual(repr(dag), '(A,B)->C')
```

**Comment by gaow** [comment]
I see ... now the names are consistent. But this reminds me of our previous discussion on packing SoS environment for another machine. Currently the absolute path is consistently used in signature. I'm afraid we will need to change or adjust that if it is still the plan to pack. 

That's a rather diligent unit-test! I should keep it up, too :) Great to know there's more opportunity to promote SoS (outside the department maybe?) !

**Comment by BoPeng** [comment]
We are still at version 0.6 and porting signature can wait till perhaps version 2.0. I would rather have a robust SoS with less features than a fancy SoS that breaks every now and then...
